name: "$name"
version: "$version"
main: kz.hxncus.mc.entitygenetics.EntityGenetics
api-version: '1.20'
depend:
  - MinesonAPI
commands:
  entitygenetics:
    aliases:
      - eg
      - egenetics
      - entityg
