name: 🐜 Bug report
description: Found something that doesn't work as expected? Raise it here!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to raise a bug! Try to be as detailed as possible to get the best support for your issue as possible."
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: What version are you using?
      placeholder: "1.0.0..."
    validations:
      required: true
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using? _(If using a minor version that isn't specified, such as 1.18.1, just select the latest version below it such as 1.18)_
      multiple: false
      options:
        - "1.21"
        - "1.20"
        - "1.19"
        - "1.18"
        - "1.17"
        - "1.16"
        - "1.15"
        - "1.14"
        - "1.13"
        - "1.12"
        - "1.11"
        - "1.10"
        - "1.9"
        - "1.8"
    validations:
      required: true
  - type: textarea
    id: what-i-did
    attributes:
      label: What I did
      description: What did you do to encounter this bug? Please be as detailed as possible!
      placeholder: |
        - I'm running a server and...
        - I ran the plugin command and...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What actually happened
      description: What happened when you did the steps above?
      placeholder: Describe what happened when you performed the steps above.
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened
      description: What should have happened when you did the steps above?
      placeholder: Describe what you would expect to happen when you perform the steps above.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Server logs and config
      description: |
        If you think it will be helpful, please include any server logs.
        Also please provide the config.yml file from `plugins/EntityGenetics/config.yml`.
      placeholder: Logs and configs (if you think it'll help!)
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Is there anything else that you think will be relevant in helping to debug this issue?
      placeholder: It only works on my machine.
    validations:
      required: false
