name: 📄 Documentation amendment
description: Is there something wrong with the documentation? Raise it here!
labels: ["documentation"]
body:
  - type: input
    id: link
    attributes:
      label: Documentation URL
      description: Which page of the documentation has an issue?
      placeholder: 'https://github.com/MinesonTeam/EntityGenetics/wiki'
    validations:
      required: true
  - type: textarea
    id: what-it-says
    attributes:
      label: What the documentation currently says
      description: What does the documentation currently say that is incorrect?
    validations:
      required: true
  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed fix
      description: What should the documentation say to fix the issue?
    validations:
      required: false
    
